language: scala

jdk: oraclejdk8

matrix:
  include:
    - env: SBT_VERSION=0.13.16
    - env: SBT_VERSION=1.0.4

script:
  - sbt -DbuildNr=$TRAVIS_BUILD_NUMBER "^^ $SBT_VERSION" clean test scripted publish

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

env:
  global:
  - secure: ic0QqjCrjUX1VgpwFuKeRbRL//3df/JQHK0FNdLa883R0BPVL4sy6WwpdAbSZOibqrPby7MJLOJmyxmDgiSss1IdzYpqf6OdxhJV1mrn5p1QTGfoxrzcaV1utHnRHHEkbN7/MxtijeafB7rHhCaad538vDWoiecmGiE+g9Y9d1VIGq2T2mE7FoHHGosLOZw2Vulejshs2gS8o9PhKwgXjOzgmBI1a9g5up/Q3rYTEpgckfrVRYNcbp+XqW3niSDsMV+Vhnwu+nowUfcbFAbuaiwTpycd+F/lUCbxDc6VRIv9qyaqAoLR/Qm/a1SINu1muUNZck4kGhOTxRxZECwK1msSFhYTO5LttydRLwCTOPPAyQZbzARKUH1CqTi8duvlLdIZaNHAVa5DEBY52bYloFOmzh6VYLmCozhBT60Y78H/e/4qYV/mLlurB14mAAqpjv67PrKTQR1XBGgMSbsP9WZibD21eMPSeyaOStuzOJ6gRKXDd6CqiP4RoIIoZ0wORGLZSjmtSJlkWFR3+ZK42kosPB/yhZ6J16IURqhrjHujGikEMY4eanqoiduqj0gM1kiUToxrR18LuVUSNmHT2J/uzYGmhtXUKiI9HUPkIeeVVyjvprPzHYb56MKLuXxtWSMQoy/j50YyLk+XkRtVYWv09YRfewMwrmkfwKnRSUY=
  - secure: JQFvNNrvmqSXSVWAeoJ7M/zDL2LBNcL5DXpXZAoULsFrax7LSJekTfqcztDc2u1isjyA1MEQ3WK95vE0VleCFZi1bXjWO+BRM6NvN6/ESxovgHLICypgDd5wLM8KDSn1q3vQ8pZRt5MpbC9vwsnHEnAhiU80l9su+lFStwDfN8do9xOYYFZJ6j7WSZr5zBVq6OMCMT5pEkVabd88BfjWmK4T/6lxL88nVV4MRtGETw3sS0PMa/uZJjc3MNB2G9FQsRg+N1fLFdqBA4H8JVz3SeZPUGhKg1O/115aR/poc6PxiGqJrCDaIGRhz1DQKOnZHnxLYTaGCtddarnr7MYaqv3Bgw0eFUXqng4WlVo6dFN9rTngyOt79rcxnQ4wmNmAUz7fzpc7JTH7E2fiNifGWxRqH26WCek60diAozy1CGBQPIxjkC5cFGYSb8Ur9+kBxRcKAqoZ/+MA4Scu45pmMsrYH0BBdpltwEjlEYF5xvPjRPDHxL7+yth3ja1qBYu6654ehfRn7FDrSgTmcfKIM5J6/jox7q7F0RmxLU+vFMFSIPhxxa+qI66ZcNCxVB57wE2T+6ulpfGj49N5ASlenU+gNOpyUZCJQrWz4MsfwHENMDp+mTwetfb+0UjEdvMq72um6zsvA2oNfg5QZjLGQkvUZ4NRO2Zkn0wPTuOnITs=
