language: scala

jdk: oraclejdk8

matrix:
  include:
    - env: SBT_VERSION=0.13.16
    - env: SBT_VERSION=1.0.4

before_script:
  - git config --global user.email "nobody@nobody.org"
  - git config --global user.name "Travis CI"
  - git remote set-url origin https://$GITHUB_TOKEN@github.com/zladovan/sbt-nomic.git

script:
  - sbt "^^ $SBT_VERSION" clean test scripted publish

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

env:
  global:
  - secure: ic0QqjCrjUX1VgpwFuKeRbRL//3df/JQHK0FNdLa883R0BPVL4sy6WwpdAbSZOibqrPby7MJLOJmyxmDgiSss1IdzYpqf6OdxhJV1mrn5p1QTGfoxrzcaV1utHnRHHEkbN7/MxtijeafB7rHhCaad538vDWoiecmGiE+g9Y9d1VIGq2T2mE7FoHHGosLOZw2Vulejshs2gS8o9PhKwgXjOzgmBI1a9g5up/Q3rYTEpgckfrVRYNcbp+XqW3niSDsMV+Vhnwu+nowUfcbFAbuaiwTpycd+F/lUCbxDc6VRIv9qyaqAoLR/Qm/a1SINu1muUNZck4kGhOTxRxZECwK1msSFhYTO5LttydRLwCTOPPAyQZbzARKUH1CqTi8duvlLdIZaNHAVa5DEBY52bYloFOmzh6VYLmCozhBT60Y78H/e/4qYV/mLlurB14mAAqpjv67PrKTQR1XBGgMSbsP9WZibD21eMPSeyaOStuzOJ6gRKXDd6CqiP4RoIIoZ0wORGLZSjmtSJlkWFR3+ZK42kosPB/yhZ6J16IURqhrjHujGikEMY4eanqoiduqj0gM1kiUToxrR18LuVUSNmHT2J/uzYGmhtXUKiI9HUPkIeeVVyjvprPzHYb56MKLuXxtWSMQoy/j50YyLk+XkRtVYWv09YRfewMwrmkfwKnRSUY=
  - secure: n5URBh3yMZczRaOKob/RSxECrxl5LaixtEtz53En65h+anNq132LIJW3XNAwZxCcsJdNLWlWBlPYeBvM0bUuSZZu3YDasLrtPV2aOJ60hCss6ESZXW6zz/X9mqQ0/Cz+7+GXuMJZpU5n10rvctpmi8iTy8sa6+KHueKkiOavLBcP3wpmjDg0oi5huSplY5N3eoRGtbDpq1tX5Z2XOsEqEPGHCW++p7raIfl/BjyaXERRAVsPNfBlJz/G6TZ9zCiSQajjNCkz68PQr4z5HD4blxlxbObGOOVX+BRWR0dVCdK4VbVm08aB8UMS2GSPdUkETOYwt29ZnbOAG1dMAQBSTh3uOb2kyrRXG/NLqkIyzW9BD+tSNK9J/fyu049ALS8JO3qUvKq8NO7fJgV9Otj+7y4gt1kL1OLfkfOkdr9uH2gSw6dSkY+60ICxEmE2wUyimWJ8rmmMXmo7gMHi2fQTfXUa+aWWE35uZJQ4kbbGE1yiY3DqvVBTIfy3ijDKNidJBxuFoTqWfZ3cSN8rupVuX2wYc7EDWWB4IkECraV/2uSdNXL3nNJ3cLH8HNR2DTPOFu1m66CH5IdPTOWD6t3/MnfXv2Cohrj74DrRuEEwW2/268rHmF5aqB608NjWeb/kBBCIVKPsqkj7IELyP3bnIlK8CRTJAojewzhoO0mHEgE=
  - secure: dYnqlcd7TmhgMIAsF1CiyzvGMF409l1v4QxsNBqBnWBVMyug1LXMtcgRWslb7ucVDUIxXv4CEPZd8TEKr16YMvm9+Ds56bhGtw5ohGkJaExeJYGYhGbmhdZ3bo/2kJAzlV0FS0itnls8Uh2Jrm8HDagwfo2GeSAcRAE6/NXtw/o8/YCHWlBGbxFyScRNgSGqwF9MCQfjB9vlYUH3OtceSwhjhH2UKEJyt860bwhhalUKNrWQtn4w435AGl0aJs+VJXXjB0GrSwpU4cvrIjQLHg+uHugitd88TKxIFYg+VfzT2lCdgGbf0Y9ynaU0UX0F+i6cgZ5YxQH1n94wBra+bdryZ0pRshBHMOOahEra9jIPl4VO5BbejM9RO4UDpmRU9Ej5Qhn1cRmP0ug9iwWqiTZnbafjJNOui+OInpzKKoIcQZI8MraIhlqNGhi9OF++aWPhug/QqKOfTn1Mct5wCK7qR1K41F5YYtFo2emumK9Y0sJ0d+4/Qkj2YfkURcpnL1pfq4r5HH88gXJUs3uwTvUweDYQ+pP1Z1eW48KY3cypF2TCZbhCXkHJhipcwhEjgykcMD74lk7PvgzG8JeCvS6O7TmsaBHUDTZL3YEk4IlzMlR9/ZtniUXbGvECUpeVuP0Z5hSne2PZ+NxG3T3IMt3KtYMOePTIW9mMqlXfaCs=

branches:
  except:
  - /^v\d+\.\d+.*/