language: scala

jdk: oraclejdk8

matrix:
  include:
    - env: SBT_VERSION=0.13.16
    - env: SBT_VERSION=1.0.4

script:
  - sbt "^^ $SBT_VERSION" clean test scripted

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete